user1 = User.create(first_name: "joe", last_name: "joe", username: "joe", email: "joe@gmail.com", password: "password")
user2 = User.create(first_name: "kiv", last_name: "joe", username: "kiv", email: "kiv@gmail.com", password: "password")
user3 = User.create(first_name: "carlos", last_name: "joe", username: "carlos", email: "carlos@gmail.com", password: "password")
user4 = User.create(first_name: "alex", last_name: "joe", username: "alex", email: "alex@gmail.com", password: "password")
user5 = User.create(first_name: "jason", last_name: "joe", username: "jason", email: "jason@gmail.com", password: "password")
user6 = User.create(first_name: "tom", last_name: "joe", username: "tom", email: "tom@gmail.com", password: "password")

Skill.create(title: "String", category: "Music", img_url: "https://images.pexels.com/photos/111287/pexels-photo-111287.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Brass", category: "Music", img_url: "https://images.pexels.com/photos/45243/saxophone-music-gold-gloss-45243.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Woodwind", category: "Music", img_url: "https://images.pexels.com/photos/30717/pexels-photo-30717.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Percussion", category: "Music", img_url: "https://images.pexels.com/photos/210799/pexels-photo-210799.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Keyboard", category: "Music", img_url: "https://images.pexels.com/photos/48620/pexels-photo-48620.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Music Production", category: "Music", img_url: "https://images.pexels.com/photos/87351/pexels-photo-87351.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Ear Pitch", category: "Music", img_url: "https://images.pexels.com/photos/38894/pexels-photo-38894.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Composition", category: "Music", img_url: "https://images.pexels.com/photos/164821/pexels-photo-164821.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Improvisation", category: "Music", img_url: "https://images.pexels.com/photos/30717/pexels-photo-30717.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Music", img_url: "https://images.pexels.com/photos/30222/pexels-photo-30222.jpg?h=350&auto=compress&cs=tinysrgb")

Skill.create(title: "Aquatic Sports", category: "Sports", img_url: "https://images.pexels.com/photos/8983/pexels-photo.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Gymnastics", category: "Sports", img_url: "https://images.pexels.com/photos/241456/pexels-photo-241456.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Martial Arts", category: "Sports", img_url: "https://images.pexels.com/photos/165939/pexels-photo-165939.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Track and Field", category: "Sports", img_url: "https://images.pexels.com/photos/28554/pexels-photo-28554.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "X-Games", category: "Sports", img_url: "https://images.pexels.com/photos/305250/pexels-photo-305250.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Teams Sports", category: "Sports", img_url: "https://images.pexels.com/photos/262524/pexels-photo-262524.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Sports", img_url: "https://images.pexels.com/photos/94624/pexels-photo-94624.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb")


Skill.create(title: "Cardio", category: "Fitness", img_url: "https://images.pexels.com/photos/29578/pexels-photo.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Weightlifting", category: "Fitness", img_url: "https://images.pexels.com/photos/17840/pexels-photo.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Nutrition", category: "Fitness", img_url: "https://images.pexels.com/photos/407110/pexels-photo-407110.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Supplements", category: "Fitness", img_url: "https://images.pexels.com/photos/33355/capsule-pill-health-medicine.jpg?w=940&h=650&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Fitness", img_url: "https://images.pexels.com/photos/305239/pexels-photo-305239.jpeg?h=350&auto=compress&cs=tinysrgb")

Skill.create(title: "SAT", category: "Education", img_url: "https://images.pexels.com/photos/159353/survey-opinion-research-voting-fill-159353.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "GED", category: "Education", img_url: "https://images.pexels.com/photos/262485/pexels-photo-262485.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Science", category: "Education", img_url: "https://images.pexels.com/photos/256262/pexels-photo-256262.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Problem Solving", category: "Education", img_url: "https://images.pexels.com/photos/355988/pexels-photo-355988.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Education", img_url: "https://images.pexels.com/photos/187107/pexels-photo-187107.jpeg?h=350&auto=compress&cs=tinysrgb")

Skill.create(title: "Asian Cuisine", category: "Cooking", img_url: "https://images.pexels.com/photos/218769/pexels-photo-218769.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "South American Cusine", category: "Cooking", img_url: "https://images.pexels.com/photos/5317/food-salad-restaurant-person.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Pasta 101", category: "Cooking", img_url: "https://images.pexels.com/photos/8500/food-dinner-pasta-spaghetti-8500.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Mixology", category: "Cooking", img_url: "https://images.pexels.com/photos/132737/pexels-photo-132737.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Italian Cuisine", category: "Cooking", img_url: "https://images.pexels.com/photos/2232/vegetables-italian-pizza-restaurant.jpg?w=940&h=650&auto=compress&cs=tinysrgb")
Skill.create(title: "Wine Tasting", category: "Cooking", img_url: "https://images.pexels.com/photos/177602/pexels-photo-177602.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Cooking", img_url: "https://images.pexels.com/photos/6549/food-vacation-boats-lunch.jpg?h=350&auto=compress&cs=tinysrgb")

Skill.create(title: "Computer Programming", category: "Technology", img_url: "https://images.pexels.com/photos/90807/pexels-photo-90807.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Engineering", category: "Technology", img_url: "https://images.pexels.com/photos/132700/pexels-photo-132700.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Web Design", category: "Technology", img_url: "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "UI/UX", category: "Technology", img_url: "https://images.pexels.com/photos/326514/pexels-photo-326514.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Big Data", category: "Technology", img_url: "https://images.pexels.com/photos/225769/pexels-photo-225769.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Technology", img_url: "https://images.pexels.com/photos/90807/pexels-photo-90807.jpeg?h=350&auto=compress&cs=tinysrgb")

user5.posts.create(skill_id: 13, description: "Attained my blackbelt at the age of 13, my hands are lethal")

40.times do
Post.create(skill_id: rand(1...4), creator_id: rand(1...3), description: Faker::Music.instrument)
end

user4.skills.create(skill_id: 18, description: "I've been running on and off for about 15 years. My longest run has been a little over 8 miles but my usual distance is around 3 miles. My average pace is a 8:30 mile. I practice proper form and would love to teach you in exchange for some sweet skills!")
user4.skills.create(skill_id: 14, description: "I've been running on and off for about 15 years. My longest run has been a little over 8 miles but my usual distance is around 3 miles. My average pace is a 8:30 mile. I practice proper form and would love to teach you in exchange for some sweet skills! I'm not an olympian or anything but I'm sure I can improve your run skills.")
user4.skills.create(skill_id: 9, description: "What will I do next? Who knows! That's how good I am at improvisation. Now, I can't promise that I'll be funny but I can promise I will make everything very awkward and probably asked politely to leave.")
user4.skills.create(skill_id: 3, description: "If you're looking to learn how to play the clarinet, I'm your guy! Let me teach you the difference between a C flat and a B sharp so that you can BE SHARP. Ehhhh, haha. Jk, but really. Lemme teach you and offer me something cool to learn in return. Let's hook up!")
user4.skills.create(skill_id: 16, description: "I'm pretty decent at basketball. Not so much the scoring or the passing or the dribbling but I'm pretty good at the part where you sweat all day and feel like your lungs are about to explode. If that sounds like your cup of tea, hit me up and let's swap some skills!")
user4.skills.create(skill_id: 5, description: "Yo, I'm the Elton John of Bushwick. Let me have the chance to teach you Tiny Dancer but in a way that no one has heard of before so that you can keep your street cred. Throw me some skills you can barter with and I'll think about it. I'm always looking for new ways to validate how unique I am and not like every other hipster in the 'shwick. Looking forward to hearing for you or whatever.")

user3.posts.create(skill_id: 1, description: "Grad student from Berklee College of music, proficient in Classical Guitar. Available during the weekends!")
user3.posts.create(skill_id: 3, description: "I have ghostwritten music for local singers, and I'm currently recording my own guitar solo album")
user3.posts.create(skill_id: 29, description: "Originally from Mexico, I have been taught how to cook fantastic South American cusine ranging from Mexico to Argentina")
user3.posts.create(skill_id: 28, description: "Learned how to cook asian dishes during my time spent in Japan")
user3.posts.create(skill_id: 23, description: "Have been tutoring for the past year, extensive knowledge in strategies to succeed in SAT's")
user3.posts.create(skill_id: 25, description: "Graduated fomr DBC, able to teach Ruby/Rails and Javascript")
