user = User.create(first_name: "joe", last_name: "joe", username: "joe", email: "joe@gmail.com", password: "password")
user = User.create(first_name: "kiv", last_name: "joe", username: "kiv", email: "kiv@gmail.com", password: "password")
user = User.create(first_name: "carlos", last_name: "joe", username: "carlos", email: "carlos@gmail.com", password: "password")
user = User.create(first_name: "alex", last_name: "joe", username: "alex", email: "alex@gmail.com", password: "password")
user = User.create(first_name: "jason", last_name: "joe", username: "jason", email: "jason@gmail.com", password: "password")
user = User.create(first_name: "tom", last_name: "joe", username: "tom", email: "tom@gmail.com", password: "password")
skill = Skill.create(title: "test", category: "testing")
# post = skill.
# user.apprenticeships.create(requestor_id: 1, post_id: 1)

Skill.create(title: "String", category: "Music")
Skill.create(title: "Brass", category: "Music")
Skill.create(title: "Woodwind", category: "Music")
Skill.create(title: "Percussion", category: "Music")
Skill.create(title: "Keyboard", category: "Music")
Skill.create(title: "Music Production", category: "Music")
Skill.create(title: "Ear Pitch", category: "Music")
Skill.create(title: "Composition", category: "Music")
Skill.create(title: "Improvisation", category: "Music")
Skill.create(title: "Other", category: "Music")

Skill.create(title: "Aquatic Sports", category: "Sports")
Skill.create(title: "Gymnastics", category: "Sports")
Skill.create(title: "Martial Arts", category: "Sports")
Skill.create(title: "Track and Field", category: "Sports")
Skill.create(title: "X-Games", category: "Sports")
Skill.create(title: "Teams Sports", category: "Sports")
Skill.create(title: "Other", category: "Sports")

Skill.create(title: "Dieting", category: "Fitness")
Skill.create(title: "Cardio", category: "Fitness")
Skill.create(title: "Weightlifting", category: "Fitness")
Skill.create(title: "Nutrition", category: "Fitness")
Skill.create(title: "Supplements", category: "Fitness")
Skill.create(title: "Other", category: "Fitness")

Skill.create(title: "SAT", category: "Education")
Skill.create(title: "GED", category: "Education")
Skill.create(title: "Science", category: "Education")
Skill.create(title: "Problem Solving", category: "Education")
Skill.create(title: "Other", category: "Education")

Skill.create(title: "Asian Cusine", category: "Cooking")
Skill.create(title: "South American Cusine", category: "Cooking")
Skill.create(title: "Pasta 101", category: "Cooking")
Skill.create(title: "Mixology", category: "Cooking")
Skill.create(title: "Bartending", category: "Cooking")
Skill.create(title: "Italian Cusine", category: "Cooking")
Skill.create(title: "Wine Tasting", category: "Cooking")
Skill.create(title: "Other", category: "Cooking")

Skill.create(title: "Computer Programming", category: "Technology")
Skill.create(title: "Engineering", category: "Technology")
Skill.create(title: "Web Design", category: "Technology")
Skill.create(title: "UI/UX", category: "Technology")
Skill.create(title: "Big Data", category: "Technology")
Skill.create(title: "Other", category: "Technology")
