user1 = User.create(first_name: "joe", last_name: "joe", username: "joe", email: "joe@gmail.com", password: "password")
user2 = User.create(first_name: "Kiv", last_name: "Smith", username: "kiv", email: "kiv@gmail.com", password: "password")
user3 = User.create(first_name: "Carlos", last_name: "Smith", username: "carlos", email: "carlos@gmail.com", password: "password")
user4 = User.create(first_name: "Alex", last_name: "Smith", username: "alex", email: "alex@gmail.com", password: "password")
user5 = User.create(first_name: "Jason", last_name: "Smith", username: "jason", email: "jason@gmail.com", password: "password")
user6 = User.create(first_name: "Tom", last_name: "Smith", username: "tom", email: "tom@gmail.com", password: "password")

Skill.create(title: "String Instruments", category: "Music", img_url: "https://images.pexels.com/photos/111287/pexels-photo-111287.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Brass Instruments", category: "Music", img_url: "https://images.pexels.com/photos/45243/saxophone-music-gold-gloss-45243.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Woodwind Instruments", category: "Music", img_url: "https://images.pexels.com/photos/30717/pexels-photo-30717.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Percussion", category: "Music", img_url: "https://images.pexels.com/photos/210799/pexels-photo-210799.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Keyboard", category: "Music", img_url: "https://images.pexels.com/photos/48620/pexels-photo-48620.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Music Production", category: "Music", img_url: "https://images.pexels.com/photos/87351/pexels-photo-87351.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Composition", category: "Music", img_url: "https://images.pexels.com/photos/164821/pexels-photo-164821.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Music", img_url: "https://images.pexels.com/photos/30222/pexels-photo-30222.jpg?h=350&auto=compress&cs=tinysrgb")

Skill.create(title: "Aquatic Sports", category: "Sports", img_url: "https://images.pexels.com/photos/8983/pexels-photo.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Gymnastics", category: "Sports", img_url: "https://images.pexels.com/photos/241456/pexels-photo-241456.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Martial Arts", category: "Sports", img_url: "https://images.pexels.com/photos/165939/pexels-photo-165939.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Track and Field", category: "Sports", img_url: "https://images.pexels.com/photos/28554/pexels-photo-28554.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "X-Games", category: "Sports", img_url: "https://images.pexels.com/photos/305250/pexels-photo-305250.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Teams Sports", category: "Sports", img_url: "https://images.pexels.com/photos/262524/pexels-photo-262524.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Sports", img_url: "https://images.pexels.com/photos/94624/pexels-photo-94624.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb")


Skill.create(title: "Cardio/Anaerobic Fitness", category: "Fitness", img_url: "https://images.pexels.com/photos/29578/pexels-photo.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Weightlifting", category: "Fitness", img_url: "https://images.pexels.com/photos/17840/pexels-photo.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Nutrition", category: "Fitness", img_url: "https://images.pexels.com/photos/407110/pexels-photo-407110.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Supplements", category: "Fitness", img_url: "https://images.pexels.com/photos/33355/capsule-pill-health-medicine.jpg?w=940&h=650&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Fitness", img_url: "https://images.pexels.com/photos/305239/pexels-photo-305239.jpeg?h=350&auto=compress&cs=tinysrgb")

Skill.create(title: "SAT", category: "Education", img_url: "https://images.pexels.com/photos/159353/survey-opinion-research-voting-fill-159353.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "GED", category: "Education", img_url: "https://images.pexels.com/photos/262485/pexels-photo-262485.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Science", category: "Education", img_url: "https://images.pexels.com/photos/256262/pexels-photo-256262.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Problem Solving", category: "Education", img_url: "https://images.pexels.com/photos/355988/pexels-photo-355988.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Education", img_url: "https://images.pexels.com/photos/187107/pexels-photo-187107.jpeg?h=350&auto=compress&cs=tinysrgb")

Skill.create(title: "Asian Cuisine", category: "Cooking", img_url: "https://images.pexels.com/photos/218769/pexels-photo-218769.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "South American Cusine", category: "Cooking", img_url: "https://images.pexels.com/photos/5317/food-salad-restaurant-person.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Pasta 101", category: "Cooking", img_url: "https://images.pexels.com/photos/8500/food-dinner-pasta-spaghetti-8500.jpg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Mixology", category: "Cooking", img_url: "https://images.pexels.com/photos/132737/pexels-photo-132737.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Italian Cuisine", category: "Cooking", img_url: "https://images.pexels.com/photos/2232/vegetables-italian-pizza-restaurant.jpg?w=940&h=650&auto=compress&cs=tinysrgb")
Skill.create(title: "Wine Tasting", category: "Cooking", img_url: "https://images.pexels.com/photos/177602/pexels-photo-177602.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Cooking", img_url: "https://images.pexels.com/photos/6549/food-vacation-boats-lunch.jpg?h=350&auto=compress&cs=tinysrgb")

Skill.create(title: "Computer Programming", category: "Technology", img_url: "https://images.pexels.com/photos/90807/pexels-photo-90807.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Engineering", category: "Technology", img_url: "https://images.pexels.com/photos/132700/pexels-photo-132700.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "UI/UX", category: "Technology", img_url: "https://images.pexels.com/photos/326514/pexels-photo-326514.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Big Data", category: "Technology", img_url: "https://images.pexels.com/photos/225769/pexels-photo-225769.jpeg?h=350&auto=compress&cs=tinysrgb")
Skill.create(title: "Other", category: "Technology", img_url: "https://images.pexels.com/photos/90807/pexels-photo-90807.jpeg?h=350&auto=compress&cs=tinysrgb")

user5.posts.create(skill_id: 13, description: "Attained my blackbelt at the age of 13, my hands are lethal")
user5.posts.create(skill_id: 18, description: "I spend 3 out of 7 days committing myself to cardio. My go to machine is the stair master. I enjoy climbing the Empire State building. After completing this climb, I then go into a ab circuit, where I do v-ups, crunches, reverse crunches, plank, side to side plank, then hanging leg lifts to the highest elevation I can. I then do goblin swats for 3 sets with a 45 pound weight, 10 resp each set. By this time, my entire shirt is drenched with sweat.")
user5.posts.create(skill_id: 19, description: "I spend 3 out of 7 days lifting. My goal during every session is to push my body to fatigue and end the session by doing dips until failure. During the session, I start with 3 chest exercises, flat bench press, chest fly machine, then machine chest press. Afterwards I move to my back, with machine rows, lat-pull downs, and close grip rows. Then I do tricep pull downs, shoulder raises and a ab circuit. Ending with dips. I have grown from doing no dips to a max of 30 dips.")
user5.posts.create(skill_id: 20, description: "I started my macro journey 10 weeks ago. My intentions with measuring my macro intake was to gauge my metabolic rate. Understanding how my body reacts to certain foods and caloric intake gave me the knowledge to draft an efficient diet that I enjoyed. As time passed and I became accustomed to by daily allowance of calories, I have now pushed myself further and became intermediate fasting. My goal is to reduce my overall body-fat percentage. Join me and become the best version of yourself.")
user5.posts.create(skill_id: 21, description: "The daily nutrition that I find essential is protein with BCAA. BCAA aka Branched-Chain Amino Acid, allows for accelerated muscle recovery. The best part is that it allows for muscle growth while in a caloric deficit. It is perfect for those who want to lose weight without compromising one’s strength. However, the most important thing is still sleep. No matter how many supplements you take, if you don't have healthy sleep regime your body will not be able to react to the supplements to its full potential.")

user4.posts.create(skill_id: 18, description: "I've been running on and off for about 15 years. My longest run has been a little over 8 miles but my usual distance is around 3 miles. My average pace is a 8:30 mile. I practice proper form and would love to teach you in exchange for some sweet skills!")
user4.posts.create(skill_id: 14, description: "I used to compete in High School and College and have one national competitions. I have a fantastic routine and can help you reach your goals!")
user4.posts.create(skill_id: 9, description: "What will I do next? Who knows! That's how good I am at improvisation. Now, I can't promise that I'll be funny but I can promise I will make everything very awkward and probably asked politely to leave.")
user4.posts.create(skill_id: 3, description: "If you're looking to learn how to play the clarinet, I'm your guy! Let me teach you the difference between a C flat and a B sharp so that you can BE SHARP. Ehhhh, haha. Jk, but really. Lemme teach you and offer me something cool to learn in return. Let's hook up!")
user4.posts.create(skill_id: 16, description: "I'm pretty decent at basketball. Not so much the scoring or the passing or the dribbling but I'm pretty good at the part where you sweat all day and feel like your lungs are about to explode. If that sounds like your cup of tea, hit me up and let's swap some skills!")
user4.posts.create(skill_id: 5, description: "Yo, I'm the Elton John of Bushwick. Let me have the chance to teach you Tiny Dancer but in a way that no one has heard of before so that you can keep your street cred. Throw me some skills you can barter with and I'll think about it. I'm always looking for new ways to validate how unique I am and not like every other hipster in the 'shwick. Looking forward to hearing for you or whatever.")

user3.posts.create(skill_id: 1, description: "Grad student from Berklee College of music, proficient in Classical Guitar. Available during the weekends!")
user3.posts.create(skill_id: 3, description: "I have ghostwritten music for local singers, and I'm currently recording my own guitar solo album")
user3.posts.create(skill_id: 29, description: "Originally from Mexico, I have been taught how to cook fantastic South American cusine ranging from Mexico to Argentina")
user3.posts.create(skill_id: 28, description: "Learned how to cook asian dishes during my time spent in Japan")
user3.posts.create(skill_id: 23, description: "Have been tutoring for the past year, extensive knowledge in strategies to succeed in SAT's")
user3.posts.create(skill_id: 25, description: "Graduated fomr DBC, able to teach Ruby/Rails and Javascript")
